version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: packages/api/Dockerfile
    ports:
      - "3000:3000"
  okta:
    build:
      context: .
      dockerfile: packages/okta/Dockerfile
    ports:
      - "4000:4000"
