version: '3.8'
services:
  okta:
    build: ./packages/okta
    ports:
      - "4000:4000"
  o365:
    build: ./packages/o365
    ports:
      - "4001:4001"
  api:
    build: ./packages/api
    ports:
      - "3000:3000"
